services:
  - type: web
    name: ezstream-client
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    buildFilter:
      paths:
      - src/**
      - public/**
      - package.json
      - next.config.js 