import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "./components/layout/Header"
import ReduxWrapper from "@/redux/ReduxWrapper"


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// HTML-in-Canvas (used by the stream compositor) is an origin trial in Chrome;
// set the token for the deployed origin to enable it without a browser flag.
const htmlInCanvasToken = process.env.NEXT_PUBLIC_HTML_IN_CANVAS_OT_TOKEN

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      {htmlInCanvasToken && (
        <head>
          <meta httpEquiv="origin-trial" content={htmlInCanvasToken} />
        </head>
      )}
      <body className={`${inter.variable} antialiased`}>
        <ReduxWrapper>
          <Header />
          {children}
        </ReduxWrapper>
      </body>
    </html>
  )
}