import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Header from "./components/layout/Header"
import ReduxWrapper from "@/redux/ReduxWrapper"
import SlidingDiv from "./components/ui/slidingDiv"


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <ReduxWrapper>
          <Header />
          {children}
        </ReduxWrapper>
      </body>
    </html>
  )
}